# Generated by Django 2.2.7 on 2019-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='tip',
            field=models.CharField(choices=[(0, 'private'), (1, 'state')], max_length=5),
        ),
    ]
