# Generated by Django 2.2.7 on 2019-11-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191120_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='tip',
            field=models.CharField(choices=[('private', 'private'), ('state', 'state')], max_length=50),
        ),
    ]
