# Generated by Django 2.2.7 on 2019-11-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191120_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='adrress',
            new_name='address',
        ),
    ]
