# Generated by Django 2.2.7 on 2019-11-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191125_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='number',
            field=models.CharField(blank='True', max_length=120),
        ),
        migrations.AddField(
            model_name='doctor',
            name='number',
            field=models.CharField(blank='True', max_length=120),
        ),
    ]
