# Generated by Django 2.2.5 on 2019-12-02 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0009_auto_20191130_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='joiners',
            field=models.ManyToManyField(blank=True, related_name='voting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinic',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
